#!/usr/bin/env python3
import os
import sys
cm = None
cm = sys.argv[1]
bash_command = ["cd " + cm, "git status"]
result_os = os.popen(' && '.join(bash_command)).read()
#is_change = False
for result in result_os.split('\n'):
    if result.find("modified") != -1:
        prepare_result = result.replace('\tmodified: ', '')
        prepare_result = prepare_result.replace(' ', '') 
        print(cm+prepare_result)
#        break